// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhBP29D9Q0XnFG6m1OoABsfGHljQrtEVk',
    appId: '1:246134478921:web:b5392150ca7707a0af8798',
    messagingSenderId: '246134478921',
    projectId: 'speak-guard',
    authDomain: 'speak-guard.firebaseapp.com',
    storageBucket: 'speak-guard.appspot.com',
    measurementId: 'G-QQ6H6SQC0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4FeJqLdKeepcGAzy2CMOypzzzL7owk2s',
    appId: '1:246134478921:android:facda22b148ffc21af8798',
    messagingSenderId: '246134478921',
    projectId: 'speak-guard',
    storageBucket: 'speak-guard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5vBBouUPA8yq9kH29QX-UWnHG9ztzhrM',
    appId: '1:246134478921:ios:b455552b75cf1ec0af8798',
    messagingSenderId: '246134478921',
    projectId: 'speak-guard',
    storageBucket: 'speak-guard.appspot.com',
    iosBundleId: 'com.example.speakGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5vBBouUPA8yq9kH29QX-UWnHG9ztzhrM',
    appId: '1:246134478921:ios:801e7abadbea4672af8798',
    messagingSenderId: '246134478921',
    projectId: 'speak-guard',
    storageBucket: 'speak-guard.appspot.com',
    iosBundleId: 'com.example.speakGuard.RunnerTests',
  );
}
